### ISSUE TITLE
Submit form externally

### ISSUE THREAD

**Issue by RyanEwen** [MikeIbberson/bambora-material-ui#13]
Is there an easy way to tokenization externally, so that I don't need to use a Submit button in my form? I am working on a payment screen with its own 'Submit order' button on it, and I need to try and tokenize the card when that is clicked, instead of using a button within the Bambora form.

**Comment by RyanEwen** [comment]
Looking at the code, one way I could see this working is by exposing a ref to the <form /> so that I could trigger a submit on it. Even better would be to expose `remoteForm` somehow. Maybe it's accessible already but I am not seeing it (I'm fairly new to React).

**Comment by MikeIbberson** [comment]
It might be worthwhile supporting a custom ref and forwarding it into the withCheckout HOC. That way, if you don't need to control the submit externally, you could just leave the component to do it's own thing. Otherwise, the ref you provide would be the one that gets createToken and then can be called programmatically. Do you think that would suit your needs well?

Alternatively, you could potentially piece something together that hides the submit with CSS and triggers it using vanilla JS. I'm not really a fan of such a hacky solution, but if you're pressed for time it might be a workaround worth exploring!

If you like the ref idea, I can take a look this week and get a PR ready.

**Comment by RyanEwen** [comment]
The ref option would work well, and in the mean time I can try the CSS solution :)

**Comment by MikeIbberson** [comment]
Evening!

Got a small PR for this if you want to review the storybook file to make sure the implementation is as you expected (https://github.com/MikeIbberson/bambora-material-ui/pull/15). Mainly, it just now accepts a ref prop on the form component.

I will publish in the AM if that looks good. I know there's still an issue with the prop errors that I will clear up too.

**Comment by RyanEwen** [comment]
Looks good to me!

Thanks

**Comment by MikeIbberson** [comment]
Awesome. You should now be able to download version 1.1.10 with this functionality!

**Comment by MikeIbberson** [comment]
I'm going to close this issue now, but let me know if further changes are required for submitting outside the form.
